# Generated by Django 4.2.16 on 2024-10-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('foto', models.ImageField(upload_to='img/fud', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Состав')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('foto', models.ImageField(upload_to='img/fud', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Состав')),
                ('fud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пицца', to='kinoteatr.fud')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('foto', models.ImageField(upload_to='img/fud', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Состав')),
                ('fud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Напитки', to='kinoteatr.fud')),
            ],
        ),
        migrations.CreateModel(
            name='A_treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('foto', models.ImageField(upload_to='img/fud', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Состав')),
                ('fud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Лакомство', to='kinoteatr.fud')),
            ],
        ),
    ]
