# Generated by Django 4.2.16 on 2024-10-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_treat',
            name='foto',
            field=models.ImageField(upload_to='media/img/fud', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='foto',
            field=models.ImageField(upload_to='media/img/fud', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='fud',
            name='foto',
            field=models.ImageField(upload_to='media/img/fud/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='foto',
            field=models.ImageField(upload_to='media/img/fud', verbose_name='Картинка'),
        ),
    ]
