# Generated by Django 4.2.16 on 2024-10-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0002_acter_film_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='data',
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год выхода в прокат'),
        ),
        migrations.AlterField(
            model_name='today',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Время сеансов'),
        ),
    ]
