# Generated by Django 4.2.16 on 2024-10-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0003_remove_film_data_film_year_alter_today_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='foto',
        ),
        migrations.CreateModel(
            name='Foto_pompeii_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/pompeii_film', verbose_name='Картинка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_pompeii', to='kinoteatr.film')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_moana_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/moana_film', verbose_name='Картинка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_moana', to='kinoteatr.film')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_greyhound_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/greyhound_film', verbose_name='Картинка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_greyhound', to='kinoteatr.film')),
            ],
        ),
    ]
