# Generated by Django 4.2.16 on 2024-10-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0004_remove_film_foto_foto_pompeii_film_foto_moana_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto_greyhound_film',
            old_name='film',
            new_name='film2',
        ),
        migrations.RenameField(
            model_name='foto_moana_film',
            old_name='film',
            new_name='film1',
        ),
        migrations.RenameField(
            model_name='foto_pompeii_film',
            old_name='film',
            new_name='film3',
        ),
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Возраст просмотра'),
        ),
    ]
