# Generated by Django 4.2.16 on 2024-10-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0005_rename_film_foto_greyhound_film_film2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_pompeii_acter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/pompeii_film', verbose_name='Картинка')),
                ('film_acter3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_pompeii_acter', to='kinoteatr.acter')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_moana_acter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/moana_film', verbose_name='Картинка')),
                ('film_acter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_moana_acter', to='kinoteatr.acter')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_greyhound_acter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/greyhound_film', verbose_name='Картинка')),
                ('film_acter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_greyhound_acter', to='kinoteatr.acter')),
            ],
        ),
    ]
