# Generated by Django 4.2.16 on 2024-10-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0006_foto_pompeii_acter_foto_moana_acter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/foto_film', verbose_name='Картинка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_film', to='kinoteatr.film')),
            ],
        ),
        migrations.RemoveField(
            model_name='foto_greyhound_film',
            name='film2',
        ),
        migrations.RemoveField(
            model_name='foto_moana_acter',
            name='film_acter1',
        ),
        migrations.RemoveField(
            model_name='foto_moana_film',
            name='film1',
        ),
        migrations.RemoveField(
            model_name='foto_pompeii_acter',
            name='film_acter3',
        ),
        migrations.RemoveField(
            model_name='foto_pompeii_film',
            name='film3',
        ),
        migrations.AddField(
            model_name='acter',
            name='film_acter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acter', to='kinoteatr.film'),
        ),
        migrations.DeleteModel(
            name='Foto_greyhound_acter',
        ),
        migrations.DeleteModel(
            name='Foto_greyhound_film',
        ),
        migrations.DeleteModel(
            name='Foto_moana_acter',
        ),
        migrations.DeleteModel(
            name='Foto_moana_film',
        ),
        migrations.DeleteModel(
            name='Foto_pompeii_acter',
        ),
        migrations.DeleteModel(
            name='Foto_pompeii_film',
        ),
    ]
