# Generated by Django 4.2.16 on 2024-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0007_foto_film_remove_foto_greyhound_film_film2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
