# Generated by Django 4.2.16 on 2024-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
