# Generated by Django 4.2.16 on 2024-10-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinoteatr', '0012_alter_profile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
